<?php include( "functions/criticalcss.php" ); ?>
<!DOCTYPE html>
	<html dir="ltr" lang="en-US">
	<head>
		<meta charset="UTF-8">
		<?php load_critical_css( "category" ); ?>
	</head>
	<body>
		<h1 class="category-hed">A Category Page</h1>

		<p>This page has a unique style for its heading, so that style will be included in the page’s CriticalCSS.</p>
		<p class="body-text">Integer non risus ante. Nullam in dolor enim. Ut sed ligula convallis, ullamcorper metus id, varius mi. Mauris mattis erat sit amet purus lobortis, eget sollicitudin odio placerat. Nulla fringilla accumsan erat et ullamcorper. Duis at consectetur metus. Curabitur vel fermentum purus. Donec id felis viverra justo ullamcorper consectetur. Etiam porta auctor est rhoncus tristique. Integer odio dui, aliquet sit amet mi id, placerat porta enim. Quisque tincidunt lorem sit amet lobortis porttitor. Suspendisse at dolor euismod, laoreet tellus ut, porttitor diam. Aliquam sed odio eget tortor interdum dictum.</p>
		<p class="body-text">Integer non risus ante. Nullam in dolor enim. Ut sed ligula convallis, ullamcorper metus id, varius mi. Mauris mattis erat sit amet purus lobortis, eget sollicitudin odio placerat. Nulla fringilla accumsan erat et ullamcorper. Duis at consectetur metus. Curabitur vel fermentum purus. Donec id felis viverra justo ullamcorper consectetur. Etiam porta auctor est rhoncus tristique. Integer odio dui, aliquet sit amet mi id, placerat porta enim. Quisque tincidunt lorem sit amet lobortis porttitor. Suspendisse at dolor euismod, laoreet tellus ut, porttitor diam. Aliquam sed odio eget tortor interdum dictum.</p>
		<p class="body-text">Integer non risus ante. Nullam in dolor enim. Ut sed ligula convallis, ullamcorper metus id, varius mi. Mauris mattis erat sit amet purus lobortis, eget sollicitudin odio placerat. Nulla fringilla accumsan erat et ullamcorper. Duis at consectetur metus. Curabitur vel fermentum purus. Donec id felis viverra justo ullamcorper consectetur. Etiam porta auctor est rhoncus tristique. Integer odio dui, aliquet sit amet mi id, placerat porta enim. Quisque tincidunt lorem sit amet lobortis porttitor. Suspendisse at dolor euismod, laoreet tellus ut, porttitor diam. Aliquam sed odio eget tortor interdum dictum.</p>
		<p class="body-text">Integer non risus ante. Nullam in dolor enim. Ut sed ligula convallis, ullamcorper metus id, varius mi. Mauris mattis erat sit amet purus lobortis, eget sollicitudin odio placerat. Nulla fringilla accumsan erat et ullamcorper. Duis at consectetur metus. Curabitur vel fermentum purus. Donec id felis viverra justo ullamcorper consectetur. Etiam porta auctor est rhoncus tristique. Integer odio dui, aliquet sit amet mi id, placerat porta enim. Quisque tincidunt lorem sit amet lobortis porttitor. Suspendisse at dolor euismod, laoreet tellus ut, porttitor diam. Aliquam sed odio eget tortor interdum dictum.</p>
		<p class="body-text">Integer non risus ante. Nullam in dolor enim. Ut sed ligula convallis, ullamcorper metus id, varius mi. Mauris mattis erat sit amet purus lobortis, eget sollicitudin odio placerat. Nulla fringilla accumsan erat et ullamcorper. Duis at consectetur metus. Curabitur vel fermentum purus. Donec id felis viverra justo ullamcorper consectetur. Etiam porta auctor est rhoncus tristique. Integer odio dui, aliquet sit amet mi id, placerat porta enim. Quisque tincidunt lorem sit amet lobortis porttitor. Suspendisse at dolor euismod, laoreet tellus ut, porttitor diam. Aliquam sed odio eget tortor interdum dictum.</p>
		<p class="body-text">Integer non risus ante. Nullam in dolor enim. Ut sed ligula convallis, ullamcorper metus id, varius mi. Mauris mattis erat sit amet purus lobortis, eget sollicitudin odio placerat. Nulla fringilla accumsan erat et ullamcorper. Duis at consectetur metus. Curabitur vel fermentum purus. Donec id felis viverra justo ullamcorper consectetur. Etiam porta auctor est rhoncus tristique. Integer odio dui, aliquet sit amet mi id, placerat porta enim. Quisque tincidunt lorem sit amet lobortis porttitor. Suspendisse at dolor euismod, laoreet tellus ut, porttitor diam. Aliquam sed odio eget tortor interdum dictum.</p>
	</body>
</html>
