<?php include( "functions/criticalcss.php" ); ?>
<!DOCTYPE html>
	<html dir="ltr" lang="en-US">
	<head>
		<meta charset="UTF-8">
		<?php load_critical_css( "home" ); ?>
	</head>
	<body>
		<section class="wrapper">
			<h1 class="hed">Hello there</h1>
			<p class="lead-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis at commodo lectus. Curabitur finibus, sapien in luctus sodales, eros justo imperdiet felis, eget rutrum augue est vel lacus. Nulla pellentesque orci semper urna efficitur laoreet. In hac habitasse platea dictumst. Donec blandit commodo vestibulum. Ut tristique nec mi ac cursus. Aliquam vitae sem vel lectus consequat volutpat. Donec fringilla turpis a dui consequat consectetur. Donec dignissim lacus eget sem ornare, aliquet volutpat lacus ultricies. Donec a congue lorem. Fusce vitae ultricies diam, ac posuere nisl. Morbi pulvinar vestibulum felis, vel molestie orci posuere in. Aliquam eu lacus commodo, congue neque nec, tristique metus. Proin vulputate odio vel leo vestibulum, vitae semper lectus vehicula.</p>
			<img class="image-right" src="http://bukk.it/hello.jpg" alt="hell, yes, this is dog" />
			<p class="body-text">Pellentesque eu laoreet odio, sed fringilla leo. Donec sit amet imperdiet massa. Donec eu urna nunc. Curabitur et suscipit nulla, non tempor tortor. Suspendisse sapien nulla, auctor eget hendrerit placerat, bibendum non urna. Etiam placerat mollis sodales. Pellentesque tincidunt luctus velit sed placerat. Nullam aliquam neque ac nisi interdum, ac dapibus ex posuere. Aliquam vel tortor id nisl scelerisque facilisis. Vivamus euismod dolor tristique aliquet tempor.</p>
			<p class="body-text">Integer non risus ante. Nullam in dolor enim. Ut sed ligula convallis, ullamcorper metus id, varius mi. Mauris mattis erat sit amet purus lobortis, eget sollicitudin odio placerat. Nulla fringilla accumsan erat et ullamcorper. Duis at consectetur metus. Curabitur vel fermentum purus. Donec id felis viverra justo ullamcorper consectetur. Etiam porta auctor est rhoncus tristique. Integer odio dui, aliquet sit amet mi id, placerat porta enim. Quisque tincidunt lorem sit amet lobortis porttitor. Suspendisse at dolor euismod, laoreet tellus ut, porttitor diam. Aliquam sed odio eget tortor interdum dictum.</p>
			<p class="body-text">Integer non risus ante. Nullam in dolor enim. Ut sed ligula convallis, ullamcorper metus id, varius mi. Mauris mattis erat sit amet purus lobortis, eget sollicitudin odio placerat. Nulla fringilla accumsan erat et ullamcorper. Duis at consectetur metus. Curabitur vel fermentum purus. Donec id felis viverra justo ullamcorper consectetur. Etiam porta auctor est rhoncus tristique. Integer odio dui, aliquet sit amet mi id, placerat porta enim. Quisque tincidunt lorem sit amet lobortis porttitor. Suspendisse at dolor euismod, laoreet tellus ut, porttitor diam. Aliquam sed odio eget tortor interdum dictum.</p>
			<img class="image-left" src="http://bukk.it/hellomonkey.jpg" alt="Smiling Monkey Selfie" />
			<h2 class="category-hed">Wait, there's more</h2>
			<p class="body-text">Integer non risus ante. Nullam in dolor enim. Ut sed ligula convallis, ullamcorper metus id, varius mi. Mauris mattis erat sit amet purus lobortis, eget sollicitudin odio placerat. Nulla fringilla accumsan erat et ullamcorper. Duis at consectetur metus. Curabitur vel fermentum purus. Donec id felis viverra justo ullamcorper consectetur. Etiam porta auctor est rhoncus tristique. Integer odio dui, aliquet sit amet mi id, placerat porta enim. Quisque tincidunt lorem sit amet lobortis porttitor. Suspendisse at dolor euismod, laoreet tellus ut, porttitor diam. Aliquam sed odio eget tortor interdum dictum.</p>
			<p class="body-text">Integer non risus ante. Nullam in dolor enim. Ut sed ligula convallis, ullamcorper metus id, varius mi. Mauris mattis erat sit amet purus lobortis, eget sollicitudin odio placerat. Nulla fringilla accumsan erat et ullamcorper. Duis at consectetur metus. Curabitur vel fermentum purus. Donec id felis viverra justo ullamcorper consectetur. Etiam porta auctor est rhoncus tristique. Integer odio dui, aliquet sit amet mi id, placerat porta enim. Quisque tincidunt lorem sit amet lobortis porttitor. Suspendisse at dolor euismod, laoreet tellus ut, porttitor diam. Aliquam sed odio eget tortor interdum dictum.</p>
			<p class="body-text">Integer non risus ante. Nullam in dolor enim. Ut sed ligula convallis, ullamcorper metus id, varius mi. Mauris mattis erat sit amet purus lobortis, eget sollicitudin odio placerat. Nulla fringilla accumsan erat et ullamcorper. Duis at consectetur metus. Curabitur vel fermentum purus. Donec id felis viverra justo ullamcorper consectetur. Etiam porta auctor est rhoncus tristique. Integer odio dui, aliquet sit amet mi id, placerat porta enim. Quisque tincidunt lorem sit amet lobortis porttitor. Suspendisse at dolor euismod, laoreet tellus ut, porttitor diam. Aliquam sed odio eget tortor interdum dictum.</p>
			<h3 class="category-subhed">Finally...</h3>
			<p class="body-text">Integer non risus ante. Nullam in dolor enim. Ut sed ligula convallis, ullamcorper metus id, varius mi. Mauris mattis erat sit amet purus lobortis, eget sollicitudin odio placerat. Nulla fringilla accumsan erat et ullamcorper. Duis at consectetur metus. Curabitur vel fermentum purus. Donec id felis viverra justo ullamcorper consectetur. Etiam porta auctor est rhoncus tristique. Integer odio dui, aliquet sit amet mi id, placerat porta enim. Quisque tincidunt lorem sit amet lobortis porttitor. Suspendisse at dolor euismod, laoreet tellus ut, porttitor diam. Aliquam sed odio eget tortor interdum dictum.</p>
			<p class="body-text">Integer non risus ante. Nullam in dolor enim. Ut sed ligula convallis, ullamcorper metus id, varius mi. Mauris mattis erat sit amet purus lobortis, eget sollicitudin odio placerat. Nulla fringilla accumsan erat et ullamcorper. Duis at consectetur metus. Curabitur vel fermentum purus. Donec id felis viverra justo ullamcorper consectetur. Etiam porta auctor est rhoncus tristique. Integer odio dui, aliquet sit amet mi id, placerat porta enim. Quisque tincidunt lorem sit amet lobortis porttitor. Suspendisse at dolor euismod, laoreet tellus ut, porttitor diam. Aliquam sed odio eget tortor interdum dictum.</p>
			<p class="post-script">Integer non risus ante. Nullam in dolor enim. Ut sed ligula convallis, ullamcorper metus id, varius mi. Mauris mattis erat sit amet purus lobortis, eget sollicitudin odio placerat. Nulla fringilla accumsan erat et ullamcorper. Duis at consectetur metus. Curabitur vel fermentum purus. Donec id felis viverra justo ullamcorper consectetur. Etiam porta auctor est rhoncus tristique. Integer odio dui, aliquet sit amet mi id, placerat porta enim. Quisque tincidunt lorem sit amet lobortis porttitor. Suspendisse at dolor euismod, laoreet tellus ut, porttitor diam. Aliquam sed odio eget tortor interdum dictum.</p>
		</section>
	</body>
</html>
